name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push packages to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | \
            docker login \
              -u ${{ secrets.DOCKER_USERNAME }} \
              --password-stdin

          # Build version 7.3
          docker build -t davideperozzi/php-composer:7.3 ./7.3
          docker push davideperozzi/php-composer:7.3

